'use strict'
const Joi = require('joi');

module.exports = {
  TEST_HANDLER_PL: Joi.object().keys({
    proto: Joi.string().required(),
    from_topic: Joi.string().required(),
    user_id: Joi.number().integer().required(),
  }).unknown(),
  PLAYER_PL: Joi.object().keys({
    proto: Joi.string().required(),
    user_id: Joi.number().integer().required(),
    nickname: Joi.string().required(),
    money_in_pocket: Joi.number().integer().required(),
    money_in_table: Joi.number().integer().required(),
    seat_id: Joi.number().integer().required(),
  }).unknown(),
  HAND_PL: Joi.object().keys({
    proto: Joi.string().required(),
    hand_id: Joi.number().integer().required(),
    seat_id: Joi.number().integer().required(),
    cards: Joi.array().items(Joi.string()),
    soft_point: Joi.number().integer(),
    hard_point: Joi.number().integer(),
    blackJack: Joi.boolean(),
    isPair: Joi.boolean(),
    parent_id: Joi.number().integer(),
    option: Joi.string(),
  }).unknown(),
  PLAYER_SCORE_PL: Joi.object().keys({
    proto: Joi.string().required(),
    user_id: Joi.number().integer().required(),
    seat_id: Joi.number().integer().required(),
    win_money: Joi.number().integer().required(),
    hand: Joi.array(),
  }).unknown(),
  WIN_PL: Joi.object().keys({
    proto: Joi.string().required(),
    hand_id: Joi.number().integer().required(),
    bet_money: Joi.number().integer().required(),
    win_money: Joi.number().integer().required(),
  }).unknown(),
  GCT2BLJ_REQ_JOIN_TABLE: Joi.object().keys({
    proto: Joi.string().required(),
    seq: Joi.number().integer().required(),
    area: Joi.string().required(),
    user_id: Joi.number().required(),
    from_topic: Joi.string(),
  }).unknown(),
  GWY2SVR_REQ_GAME_PLAY: Joi.object().keys({
    proto: Joi.string().required(),
    seq: Joi.number().integer().required(),
    payload: Joi.object().required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2DBA_REQ_JOIN_TABLE: Joi.object().keys({
    proto: Joi.string().required(),
    seq: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    from_topic: Joi.string(),
  }).unknown(),
  DBA2BLJ_RSP_JOIN_TABLE: Joi.object().keys({
    proto: Joi.string().required(),
    seq_back: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    money_in_pocket: Joi.number().integer().required(),
    money_in_table: Joi.number().integer().required(),
    nickname: Joi.string().required(),
    result: Joi.string().required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2GCT_RSP_JOIN_TABLE: Joi.object().keys({
    proto: Joi.string().required(),
    seq_back: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    player: Joi.object(),
    result: Joi.string().required(),
    from_topic: Joi.string(),
  }).unknown(),
  GCT2BLJ_REQ_TABLE_INFO: Joi.object().keys({
    proto: Joi.string().required(),
    seq: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    from_topic: Joi.string()
  }).unknown(),
  BLJ2GCT_RSP_TABLE_INFO: Joi.object().keys({
    proto: Joi.string().required(),
    seq_back: Joi.number().integer().required(),
    sit: Joi.array().items(Joi.object()).required(),
    stand: Joi.array().items(Joi.object()).required(),
    result: Joi.string().required(),
    from_topic: Joi.string()
  }).unknown(),
  GCT2BLJ_REQ_BUY_IN: Joi.object().keys({
    proto: Joi.string().required(),
    seq: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    buy_in: Joi.number().integer().required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2DBA_REQ_BUY_IN: Joi.object().keys({
    proto: Joi.string().required(),
    seq: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    buy_in: Joi.number().integer().required(),
    from_topic: Joi.string(),
  }).unknown(),
  DBA2BLJ_RSP_BUY_IN: Joi.object().keys({
    proto: Joi.string().required(),
    seq_back: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    money_in_pocket: Joi.number().integer().required(),
    money_in_table: Joi.number().integer().required(),
    result: Joi.string().required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2GCT_RSP_BUY_IN: Joi.object().keys({
    proto: Joi.string().required(),
    seq_back: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    money_in_pocket: Joi.number().integer().required(),
    money_in_table: Joi.number().integer().required(),
    result: Joi.string().required(),
    from_topic: Joi.string(),
  }).unknown(),
  GCT2BLJ_REQ_SIT_DOWN: Joi.object().keys({
    proto: Joi.string().required(),
    seq: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    seat_id: Joi.number().integer(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2GCT_RSP_SIT_DOWN: Joi.object().keys({
    proto: Joi.string().required(),
    seq_back: Joi.number().integer().required(),
    result: Joi.string().required(),
    from_topic: Joi.string(),
  }).unknown(),
  GCT2BLJ_REQ_BET: Joi.object().keys({
    proto: Joi.string().required(),
    seq: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    bets: Joi.object().required(),
    pair_bets: Joi.object().required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2GCT_RSP_BET: Joi.object().keys({
    proto: Joi.string().required(),
    seq_back: Joi.number().integer().required(),
    bets: Joi.array().items(Joi.object()).required(),
    pair_bets: Joi.object().required(),
    result: Joi.string().required(),
    from_topic: Joi.string()
  }).unknown(),
  GCT2BLJ_NTF_BET: Joi.object().keys({
    proto: Joi.string().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    bets: Joi.array().items(Joi.object()).required(),
    pair_bets: Joi.array().items(Joi.object()).required(),
    from_topic: Joi.string()
  }).unknown(),
  BLJ2GCT_NTF_DEAL_CARD: Joi.object().keys({
    proto: Joi.string().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    seat_id: Joi.number().integer().required(),
    hand: Joi.object().required(),
    from_topic: Joi.string()
  }).unknown(),
  BLJ2GCT_NTF_YOUR_TURN_TO_PLAY: Joi.object().keys({
    proto: Joi.string().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    seat_id: Joi.number().integer().required(),
    hand_id: Joi.number().integer().required(),
    options: Joi.array().items(Joi.string()).required(),
    from_topic: Joi.string(),
  }).unknown(),
  GCT2BLJ_REQ_PLAY: Joi.object().keys({
    proto: Joi.string().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    seat_id: Joi.number().integer().required(),
    hand_id: Joi.number().integer().required(),
    option: Joi.string().required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2GCT_RSP_PLAY: Joi.object().keys({
    proto: Joi.string().required(),
    seq_back: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    seat_id: Joi.number().integer().required(),
    hand_id: Joi.number().integer().required(),
    option: Joi.string().required(),
    result: Joi.string().required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2GCT_NTF_OTHER_PLAY: Joi.object().keys({
    proto: Joi.string().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    user_id: Joi.number().integer().required(),
    seat_id: Joi.number().integer().required(),
    hand_id: Joi.number().integer().required(),
    option: Joi.string().required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2GCT_NTF_DEALER_CARDS: Joi.object().keys({
    proto: Joi.string().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    hand: Joi.object().required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2GCT_NTF_SHOWDOWN: Joi.object().keys({
    proto: Joi.string().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    hands: Joi.array().items(Joi.object()).required(),
    dealer_hand: Joi.object().required(),
    refunds: Joi.array().items(Joi.object()).required(),
    from_topic: Joi.string(),
  }).unknown(),
  BLJ2DBA_REQ_WRITE_SCORE: Joi.object().keys({
    proto: Joi.string().required(),
    seq: Joi.number().integer().required(),
    area: Joi.string().required(),
    table_id: Joi.number().integer().required(),
    dealer_hand: Joi.object().required(),
    player_scores: Joi.array().items(Joi.object()).required(),
    from_topic: Joi.string(),
  }).unknown(),
  DBA2BLJ_RSP_WRITE_SCORE: Joi.object().keys({
    proto: Joi.string().required(),
    seq_back: Joi.number().integer().required(),
    result: Joi.string().required(),
    from_topic: Joi.string(),
  }).unknown(),
}
